/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PlacementRouteImport } from './routes/placement'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ApiCaptionJobsRouteImport } from './routes/api/caption-jobs'
import { Route as ApiCaptionProbeRouteImport } from './routes/api/caption-probe'
import { Route as ApiCaptionsRouteImport } from './routes/api/captions'
import { Route as ApiTimedtextRouteImport } from './routes/api/timedtext'
import { Route as ApiYtEdgeRouteImport } from './routes/api/yt-edge'
import { Route as OauthCallbackRouteImport } from './routes/oauth.callback'
import { Route as WatchVideoIdRouteImport } from './routes/watch.$videoId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacementRoute = PlacementRouteImport.update({
  id: '/placement',
  path: '/placement',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCaptionJobsRoute = ApiCaptionJobsRouteImport.update({
  id: '/api/caption-jobs',
  path: '/api/caption-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCaptionProbeRoute = ApiCaptionProbeRouteImport.update({
  id: '/api/caption-probe',
  path: '/api/caption-probe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCaptionsRoute = ApiCaptionsRouteImport.update({
  id: '/api/captions',
  path: '/api/captions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTimedtextRoute = ApiTimedtextRouteImport.update({
  id: '/api/timedtext',
  path: '/api/timedtext',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYtEdgeRoute = ApiYtEdgeRouteImport.update({
  id: '/api/yt-edge',
  path: '/api/yt-edge',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchVideoIdRoute = WatchVideoIdRouteImport.update({
  id: '/watch/$videoId',
  path: '/watch/$videoId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/placement': typeof PlacementRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/api/caption-jobs': typeof ApiCaptionJobsRoute
  '/api/caption-probe': typeof ApiCaptionProbeRoute
  '/api/captions': typeof ApiCaptionsRoute
  '/api/timedtext': typeof ApiTimedtextRoute
  '/api/yt-edge': typeof ApiYtEdgeRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/watch/$videoId': typeof WatchVideoIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/placement': typeof PlacementRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/api/caption-jobs': typeof ApiCaptionJobsRoute
  '/api/caption-probe': typeof ApiCaptionProbeRoute
  '/api/captions': typeof ApiCaptionsRoute
  '/api/timedtext': typeof ApiTimedtextRoute
  '/api/yt-edge': typeof ApiYtEdgeRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/watch/$videoId': typeof WatchVideoIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/placement': typeof PlacementRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/api/caption-jobs': typeof ApiCaptionJobsRoute
  '/api/caption-probe': typeof ApiCaptionProbeRoute
  '/api/captions': typeof ApiCaptionsRoute
  '/api/timedtext': typeof ApiTimedtextRoute
  '/api/yt-edge': typeof ApiYtEdgeRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/watch/$videoId': typeof WatchVideoIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/placement'
    | '/saved'
    | '/settings'
    | '/api/caption-jobs'
    | '/api/caption-probe'
    | '/api/captions'
    | '/api/timedtext'
    | '/api/yt-edge'
    | '/oauth/callback'
    | '/watch/$videoId'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/placement'
    | '/saved'
    | '/settings'
    | '/api/caption-jobs'
    | '/api/caption-probe'
    | '/api/captions'
    | '/api/timedtext'
    | '/api/yt-edge'
    | '/oauth/callback'
    | '/watch/$videoId'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/onboarding'
    | '/placement'
    | '/saved'
    | '/settings'
    | '/api/caption-jobs'
    | '/api/caption-probe'
    | '/api/captions'
    | '/api/timedtext'
    | '/api/yt-edge'
    | '/oauth/callback'
    | '/watch/$videoId'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PlacementRoute: typeof PlacementRoute
  SavedRoute: typeof SavedRoute
  SettingsRoute: typeof SettingsRoute
  ApiCaptionJobsRoute: typeof ApiCaptionJobsRoute
  ApiCaptionProbeRoute: typeof ApiCaptionProbeRoute
  ApiCaptionsRoute: typeof ApiCaptionsRoute
  ApiTimedtextRoute: typeof ApiTimedtextRoute
  ApiYtEdgeRoute: typeof ApiYtEdgeRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
  WatchVideoIdRoute: typeof WatchVideoIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/placement': {
      id: '/placement'
      path: '/placement'
      fullPath: '/placement'
      preLoaderRoute: typeof PlacementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/caption-jobs': {
      id: '/api/caption-jobs'
      path: '/api/caption-jobs'
      fullPath: '/api/caption-jobs'
      preLoaderRoute: typeof ApiCaptionJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/caption-probe': {
      id: '/api/caption-probe'
      path: '/api/caption-probe'
      fullPath: '/api/caption-probe'
      preLoaderRoute: typeof ApiCaptionProbeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/captions': {
      id: '/api/captions'
      path: '/api/captions'
      fullPath: '/api/captions'
      preLoaderRoute: typeof ApiCaptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/timedtext': {
      id: '/api/timedtext'
      path: '/api/timedtext'
      fullPath: '/api/timedtext'
      preLoaderRoute: typeof ApiTimedtextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/yt-edge': {
      id: '/api/yt-edge'
      path: '/api/yt-edge'
      fullPath: '/api/yt-edge'
      preLoaderRoute: typeof ApiYtEdgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/callback': {
      id: '/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$videoId': {
      id: '/watch/$videoId'
      path: '/watch/$videoId'
      fullPath: '/watch/$videoId'
      preLoaderRoute: typeof WatchVideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PlacementRoute: PlacementRoute,
  SavedRoute: SavedRoute,
  SettingsRoute: SettingsRoute,
  ApiCaptionJobsRoute: ApiCaptionJobsRoute,
  ApiCaptionProbeRoute: ApiCaptionProbeRoute,
  ApiCaptionsRoute: ApiCaptionsRoute,
  ApiTimedtextRoute: ApiTimedtextRoute,
  ApiYtEdgeRoute: ApiYtEdgeRoute,
  OauthCallbackRoute: OauthCallbackRoute,
  WatchVideoIdRoute: WatchVideoIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
